### ISSUE TITLE
Redoc - loading googefont from web instead from local path

### ISSUE THREAD

**Issue by dtavb** [tfranzel/drf-spectacular-sidecar#6]
Hello, maybe something is wrong in my env or this point is missing in staticfile with drf spec sidecar:

my system has no connection to the internet, thats why I deploying my project offline with sidecar.
swagger-ui is working fine, all of the required files a loaded from local (static) path, but redoc not does not for one specific file:

the /redoc loads very long, the browser debug console shows this file causes the timeout:
https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;700&family=Roboto:wght@300;400;700&display=swap

the html head is this for /redoc:
```
<head>
    <title>REST API</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;700&amp;family=Roboto:wght@300;400;700&amp;display=swap">
</head>
```

compared to /swagger-ui
```
<head>
    <title>REST API</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="/static/drf_spectacular_sidecar/swagger-ui-dist/favicon-32x32.png">
    <link rel="stylesheet" href="/static/drf_spectacular_sidecar/swagger-ui-dist/swagger-ui.css">
</head>
```

I have no idea where to fix it, because I have not found a options for this.

**Comment by tfranzel** [comment]
Hi, interesting point. Yes, we do not host the google font, so it makes sense. Not entirely sure if we should honestly. 

You have 2 choices currently. Override the template via the default django template override mechanism: https://docs.djangoproject.com/en/4.2/howto/overriding-templates/ That should be pretty simple. Just make sure your app is above drf-spectacular.

1. Just copy the our template https://github.com/tfranzel/drf-spectacular/blob/master/drf_spectacular/templates/drf_spectacular/redoc.html and remove the googlefont parts
2. edit as above but replace googlefonts domain with your own hosting

**Comment by dtavb** [comment]
hey thank you alot for the hint with template overrides, thats solves my issue with redoc.
