### ISSUE TITLE
Swagger page blank with all files accessing showing 404

### ISSUE THREAD

**Issue by xiangasshawn** [tfranzel/drf-spectacular-sidecar#7]
Hello,
Currently our project uses drf_spectacular and it works fine. I'm trying to change swagger to be available offline by introducing sidecar, but I don't know what I set wrong that caused this:
```
Refused to apply style from 'http://127.0.0.1:8000/api-static/drf_spectacular_sidecar/swagger-ui-dist/swagger-ui.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
GET http://127.0.0.1:8000/api-static/drf_spectacular_sidecar/swagger-ui-dist/swagger-ui-standalone-preset.js net::ERR_ABORTED 404 (Not Found)
GET http://127.0.0.1:8000/api-static/drf_spectacular_sidecar/swagger-ui-dist/swagger-ui-bundle.js net::ERR_ABORTED 404 (Not Found)
Refused to execute script from 'http://127.0.0.1:8000/api-static/drf_spectacular_sidecar/swagger-ui-dist/swagger-ui-bundle.js because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
Refused to execute script from 'http://127.0.0.1:8000/api-static/drf_spectacular_sidecar/swagger-ui-dist/swagger-ui-standalone-preset.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
swagger/:132  Uncaught ReferenceError: SwaggerUIBundle is not defined
```
versions involved:
drf-spectacular                             0.26.2
drf-spectacular-sidecar               2023.12.1

Settings in settings.py:
```
INSTALLED_APPS = [
    ......,

    'drf_spectacular',
    'drf_spectacular_sidecar',
]

```
```
SPECTACULAR_SETTINGS = {
   ......,

    'SWAGGER_UI_DIST': 'SIDECAR',
    'SWAGGER_UI_FAVICON_HREF': 'SIDECAR',
    'REDOC_DIST': 'SIDECAR',
}
```
urlpatterns in urls.py:
```
urlpatterns = [
    ......,

    re_path(r'^api/schema/', SpectacularAPIView.as_view(), name='schema'),
    re_path(r'^api/swagger/', SpectacularSwaggerView.as_view(), name='swagger'),
    re_path(r'^api/redoc/', SpectacularRedocView.as_view(), name='redoc'),
]
```

After `python3 manage.py collectstatic`, I can see all files properly copied to 'api-static/drf_spectacular_sidecar'. However, it seems when accessing, those files are not found.

I also tried adding more settings based on https://github.com/tfranzel/drf-spectacular/issues/797#issuecomment-1228600502, but it doesn't work either.

Please let me know what should I do to solve this. Really appreciate it!

**Comment by tfranzel** [comment]
Hi,

I think #797 is not relevant unless you have django-csp or manual CSP going on. The browser would tell the the violation in the console.

When collectstatic is correctly getting all the files, it basically has to be the routing. Are you using a reverse-proxy? Missing a  redirect? That error message looks like a 404 which return a simple html page that is obviously failing to load as it is not js.

Have you tried manually getting one of the assets from your server to see if it works? Are the admin assets working correctly (which use the same mechanism)?. I'm pretty sure this is due to a wrong config on your side. the spectacular part looks fine and works fine for a lot of people.

**Comment by xiangasshawn** [comment]
Hi,
Thanks for your help. I think I figured it out. It's a Django static file accessing issue with DEBUG mode, and I was able to see proper swagger path with "--insecure".

However, I found new issues. With self-hosting swagger page, I noticed nearly half requests missing. Any idea on what could cause this?
