### ISSUE TITLE
Earlier release

### ISSUE THREAD

**Issue by kiblik** [tfranzel/drf-spectacular-sidecar#8]
Hi,

README describes
> This is a self-updating and self-publishing repository that looks for updates once **a week**.

However, I see that releases are once a month since https://github.com/tfranzel/drf-spectacular-sidecar/commit/376c697ddb1a839c75dd4ebf8d23a98d7d70b001.

Is it possible to revert it (for every week) or is it possible to generate a new release on request?

Context:
I noticed that the latest version (`2024.3.1`) of `drf-spectacular-sidecar` contains `swagger-ui-dist` in version `5.11.8`. We already know that this version introduced the [bug](https://github.com/swagger-api/swagger-ui/issues/9645) that is breaking our deployment. The bug was already fixed and will be released next week (https://github.com/swagger-api/swagger-ui/issues/9645#issuecomment-1973141060).
It means that we would have to wait a whole month for the new version of `drf-spectacular-sidecar`.

**Comment by tfranzel** [comment]
Hi,

yes I forgot to update the README. I chose once a month because weekly did rack up too much github storage for me. 

I do not intend to change the cycle currently. All things considered, having to use a 4 weeks old SwaggerUI shouldn't be that much of a problem imho. drf-yasg currently ships with SwaggerUI 4.1.3 (2021-12-10) 😄 

However, since this is hitting a lot of people we can do a one-off release.

**Comment by kiblik** [comment]
Hi @tfranzel,

I hope that all user of `drf-yasg` are already migrating their setup 😄 `2021-12-10` sounds bit old. 

The fixed version of `swagger-ui-dist` in version 5.11.9 was already released (https://github.com/swagger-api/swagger-ui/issues/9645#issuecomment-1976043844) and works well (in our environment).
Can you please release a new version of `drf-spectacular-sidecar` with mentioned version, please?

**Comment by tfranzel** [comment]
> I hope that all user of drf-yasg are already migrating their setup 😄 2021-12-10 sounds bit old.

doubtful 😄 

new version is released. 🚀
